### YamlMime:PythonClass
uid: azure.core.exceptions.AzureError
name: AzureError
fullName: azure.core.exceptions.AzureError
module: azure.core.exceptions
inheritances:
- builtins.Exception
summary: Base exception for all errors.
constructor:
  syntax: AzureError(message, *args, **kwargs)
  parameters:
  - name: message
    description: The message object stringified as 'message' attribute
variables:
- description: The exception passed with the 'error' kwarg
  name: inner_exception
  types:
  - '[Exception](https://docs.python.org/3.6/library/exceptions.html#Exception)'
- description: The exc_type from sys.exc_info()
  name: inner_exception
- description: The exc_value from sys.exc_info()
  name: inner_exception
- description: The exc_traceback from sys.exc_info()
  name: inner_exception
- description: A string formatting of message parameter, exc_type and exc_value
  name: inner_exception
- description: A stringified version of the message parameter
  name: inner_exception
  types:
  - '[str](https://docs.python.org/3.6/library/stdtypes.html#str)'
- description: 'A token reference to continue an incomplete operation. This value
    is optional

    and will be *None* where continuation is either unavailable or not applicable.'
  name: inner_exception
  types:
  - '[str](https://docs.python.org/3.6/library/stdtypes.html#str)'
methods:
- uid: azure.core.exceptions.AzureError.raise_with_traceback
  name: raise_with_traceback
  signature: raise_with_traceback()
